ci(githooks): acommodate conditional workflows if needed in post-merge

diff --git a/ci/githooks/post-merge b/ci/githooks/post-merge
--- a/ci/githooks/post-merge
+++ b/ci/githooks/post-merge
@@ -3,34 +3,34 @@ set -e
 
 branch_name=$(git symbolic-ref --short HEAD)
 RELEASE_CHANNEL=$(git config --default '' "branch.${branch_name}.release-channel")
-KUBECONFIG=$(git config --default '' "channel.${RELEASE_CHANNEL}.kubeconfig")
-BUILD_REPO_USER=$(git config --default '' "channel.${RELEASE_CHANNEL}.build-repo-user")
-BUILD_REPO_SECRET=$(git config --default '' "channel.${RELEASE_CHANNEL}.build-repo-secret")
-BUILD_FORCE=$(git config --default '' "channel.${RELEASE_CHANNEL}.build-force")
 
-if ! [[ $RELEASE_CHANNEL ]]; then
-  exit 0
+if [[ $RELEASE_CHANNEL ]]; then
+
+  REPO_TAG=$(git describe --abbrev=0)
+  KUBECONFIG=$(git config --default '' "channel.${RELEASE_CHANNEL}.kubeconfig")
+  BUILD_REPO_USER=$(git config --default '' "channel.${RELEASE_CHANNEL}.build-repo-user")
+  BUILD_REPO_SECRET=$(git config --default '' "channel.${RELEASE_CHANNEL}.build-repo-secret")
+  BUILD_FORCE=$(git config --default '' "channel.${RELEASE_CHANNEL}.build-force")
+
+  if ! [[ $KUBECONFIG ]]; then
+    printf 'error: missing required config channel.%s.kubeconfig\n' >&2 "$RELEASE_CHANNEL"
+    exit 1
+  fi
+
+  required_missing=()
+
+  eval "$(git tag -l --format='%(contents)' "$REPO_TAG" | grep '^BUILD_.*=')"
+  test "$BUILD_APP"  || required_missing+=('BUILD_APP')
+  test "$BUILD_ID"   || required_missing+=('BUILD_ID')
+  test "$BUILD_REPO" || required_missing+=('BUILD_REPO')
+
+  if [[ ${#required_missing[*]} -gt 0 ]]; then
+    printf 'error: tag %s description missing required variables: %s\n' "$REPO_TAG" "${required_missing[*]}" >&2
+    exit 1
+  fi
+
+  printf 'post-merge: releasing into channel %s: BUILD_APP=%s BUILD_ID=%s BUILD_REPO=%s\n' "$RELEASE_CHANNEL" "$BUILD_APP" "$BUILD_ID" "$BUILD_REPO"
+
+  source $(git rev-parse --show-toplevel)/ci/workflows/service-apply-release.sh
+
 fi
-
-if ! [[ $KUBECONFIG ]]; then
-  printf 'error: missing required config channel.%s.kubeconfig\n' >&2 "$RELEASE_CHANNEL"
-  exit 1
-fi
-
-REPO_TAG=$(git describe --abbrev=0)
-
-required_missing=()
-
-eval "$(git tag -l --format='%(contents)' "$REPO_TAG" | grep '^BUILD_.*=')"
-test "$BUILD_APP"  || required_missing+=('BUILD_APP')
-test "$BUILD_ID"   || required_missing+=('BUILD_ID')
-test "$BUILD_REPO" || required_missing+=('BUILD_REPO')
-
-if [[ ${#required_missing[*]} -gt 0 ]]; then
-  printf 'error: tag %s description missing required variables: %s\n' "$REPO_TAG" "${required_missing[*]}" >&2
-  exit 1
-fi
-
-printf 'post-merge: releasing into channel %s: BUILD_APP=%s BUILD_ID=%s BUILD_REPO=%s\n' "$RELEASE_CHANNEL" "$BUILD_APP" "$BUILD_ID" "$BUILD_REPO"
-
-source $(git rev-parse --show-toplevel)/ci/workflows/service-apply-release.sh
